import { ucon, ProgressBar } from "./index";
import { stdout } from 'process';
const p1 = new ProgressBar({ width: 20, name: "Processing1" });
const p2 = new ProgressBar({ width: 20, name: "Processing2" });
(async()=>{
p1.mount();
p2.mount();
})();
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
ucon.log("1","2","3");
let n = 0;
const timer = setInterval(async () => {
  if (n > 19) return;
  p1.progress(0.1);
  //p2.progress(0.05);
  n++;
}, 1000);

// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// stdout.write("1\n");
// ucon.moveY(-100);
// stdout.re